kind: ConfigMap 
apiVersion: v1 
metadata:
  name: example-configmap 
data:
  # Configuration values can be set as key-value properties
  database: {app2.dbname}
  database_uri: {app2.dburi}
  
